version: "3.9"

services:
        
  parser:
    restart: always
    build:
      context: ./cdiscount/
    ports:
      - "5000:5000"
    depends_on:
      - splash 

  splash:
    restart: always
    image: scrapinghub/splash
    ports:
    - "8055:8050"

